version: "3.5"
services:
  backend:
    ports:
      - 8080:8080
    environment:
      DBHOST: mysql
      DBUSER: root
      DBPASSWORD: password
      DBPORT: 3306
      DBNAME: todo
    build:
      context: .
      dockerfile: Dockerfile 
    depends_on:
      - mysql 
  mysql:
    platform: linux/x86_64
    container_name: mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: todo
    volumes:
       - dbdata:/var/lib/mysql
volumes:
   dbdata:
